# docker build -t jiminu/express:0.1 -f dockerfile-express ./

FROM node:20.11
# ENV DEBIAN_FRONTEND=noninteractive
# essential install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update \ 
    && apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    wget \
    fontconfig \
    vim \
    net-tools \
    psmisc

RUN apt-get clean

WORKDIR /app