version: "3"

# services 하위로 한 묶음
services:
  mdb:
    container_name: mdb
    image: jiminu/mdb:0.2
    # env_file:
    #   - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=sample
      
      - TZ=${TZ}
    
    volumes:
      - ${CONFIG_DB}:/data/configdb
      - ${MONGODB}:/data/db
      
    restart: always
    # command: "tail -f /dev/null"
    # networks:
    #   - food_net
      
  express:
    container_name: express
    image: jiminu/express:0.5
    depends_on:
      - mdb
    restart: always
    # env_file:
    #   - ../config/.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://mdb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      
      - TZ=${TZ}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    expose:
      - ${NODE_PORT}
    # command: tail -f /dev/null
#     networks:
#       - food_net
    
# networks:
#   food_net:
#     driver: bridge