FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

# essential install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# KST
ENV TZ=Asia/Seoul
RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata \
    && ln -fs /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    wget \
    fontconfig \
    vim \
    net-tools \
    psmisc \
    openjdk-17-jdk-headless \
    locales \
    && rm -rf /var/lib/apt/lists/*

# install OpenJDK 17 and expose JAVA_HOME to shells
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH
RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> ~/.zshrc \
 && echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.zshrc

# install oh my zsh
RUN apt-get update && apt-get install -y zsh
RUN chsh -s /bin/zsh
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN perl -pi -w -e "s/plugins=.*/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g;" ~/.zshrc
RUN echo 'LS_COLORS="ow=01;36;40" && export LS_COLORS' >> ~/.zshrc

# install powerlevel10k (oh my zsh theme)
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
RUN perl -pi -w -e 's/ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/g;' ~/.zshrc 
RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc
RUN mkdir -p root/.vscode-server/data/Machine
RUN touch root/.vscode-server/data/Machine/settings.json
RUN echo '{"editor.fontFamily": "Consolas, 'Courier New', monospace, 'MesloLGS NF'",}' >> root/.vscode-server/data/Machine/settings.json

# korean font
RUN locale-gen en_US.UTF-8 ko_KR.UTF-8
RUN update-locale LANG=en_US.UTF-8 LC_CTYPE=ko_KR.UTF-8
RUN echo 'export LANG=en_US.UTF-8' >> ~/.zshrc
RUN echo 'export LC_CTYPE=ko_KR.UTF-8' >> ~/.zshrc

# # install fonts
RUN mkdir /usr/share/fonts/truetype/MesloLGS\ NF
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Regular.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Bold.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Italic.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Bold\ Italic.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
RUN fc-cache -f -v

# install node & nest
RUN mkdir -p root/.nvm
ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=22.17.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
RUN apt-get update
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias defalut $NODE_VERSION \
    && nvm use defalut \
    && apt-get install -y npm \
    && npm install -g pm2
RUN perl -pi -w -e 's/export\ NVM_DIR=.*/export\ NVM_DIR="\$HOME\/.nvm"/g;' ~/.zshrc 

RUN apt-get clean