# docker build -t jiminu/express:0.1 -f dockerfile-express ./

FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

# essential install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# KST
ENV TZ=Asia/Seoul
RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata \
    && ln -fs /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    wget \
    fontconfig \
    vim \
    net-tools \
    psmisc \
    locales \
    build-essential \
    gdb \
    openssl \
    libssl-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# install oh my zsh
RUN apt-get update && apt-get install -y zsh
RUN chsh -s /bin/zsh
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN perl -pi -w -e "s/plugins=.*/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g;" ~/.zshrc
RUN echo 'LS_COLORS="ow=01;36;40" && export LS_COLORS' >> ~/.zshrc

# install powerlevel10k (oh my zsh theme)
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
RUN perl -pi -w -e 's/ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/g;' ~/.zshrc 
RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc
RUN mkdir -p root/.vscode-server/data/Machine
RUN touch root/.vscode-server/data/Machine/settings.json
RUN echo '{"editor.fontFamily": "Consolas, 'Courier New', monospace, 'MesloLGS NF'",}' >> root/.vscode-server/data/Machine/settings.json
COPY ./.p10k.zsh /root/.p10k.zsh
RUN sed -i 's/\r$//' /root/.p10k.zsh
RUN perl -pi -w -e 's/# If you come.*/if [[ -r "\${XDG_CACHE_HOME:-\$HOME\/.cache}\/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then\n  source "\${XDG_CACHE_HOME:-\$HOME\/.cache}\/p10k-instant-prompt-\${(%):-%n}.zsh"\nfi/g' ~/.zshrc

# korean font
RUN locale-gen en_US.UTF-8 ko_KR.UTF-8
RUN update-locale LANG=en_US.UTF-8 LC_CTYPE=ko_KR.UTF-8
RUN echo 'export LANG=en_US.UTF-8' >> ~/.zshrc
RUN echo 'export LC_CTYPE=ko_KR.UTF-8' >> ~/.zshrc

# install docker
# RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# RUN echo \ 
#     "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
#     $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
# RUN apt-get update \
#     && apt-get install -y \
#     docker-ce \
#     docker-ce-cli \
#     containerd.io

# # install fonts
RUN mkdir /usr/share/fonts/truetype/MesloLGS\ NF
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Regular.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Bold.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Italic.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
RUN wget -O /usr/share/fonts/truetype/MesloLGS\ NF/MesloLGS\ NF\ Bold\ Italic.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
RUN fc-cache -f -v

# cmake build
RUN set -eux; \
    CMAKE_VER=3.25.1; \
    CMAKE_TAR="cmake-${CMAKE_VER}.tar.gz"; \
    wget -O "${CMAKE_TAR}" "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/${CMAKE_TAR}"; \
    tar -xvf "${CMAKE_TAR}"; \
    cd "cmake-${CMAKE_VER}"; \
    ./bootstrap; \
    make -j"$(nproc)"; \
    make install; \
    cd ..; \
    rm -rf "${CMAKE_TAR}" "cmake-${CMAKE_VER}";



RUN apt-get clean

RUN git config --global user.name "jiminu"
RUN git config --global user.email "jmu417@gmail.com"

# RUN rm -rf /root/.ssh/

# CMD tail -f /dev/null

# CMD [ "npm", "run", "dev"]