FROM node:20.11
# ENV DEBIAN_FRONTEND=noninteractive

# syntax=docker/dockerfile:1.6

# essential install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update \ 
    && apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    wget \
    fontconfig \
    vim \
    net-tools \
    psmisc \
    openssh-client
    
RUN mkdir -p ~/.ssh \
 && chmod 700 ~/.ssh \
 && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN apt-get clean

RUN --mount=type=ssh \
    git clone --depth 1 git@github.com:cat-investigation/express.git /app
    
WORKDIR /app

# RUN git pull
RUN npm install
RUN git checkout -- package-lock.json

RUN rm -rf /root/.ssh/

CMD [ "npm", "run", "dev"]