# services 하위로 한 묶음
services:
  db:
    container_name: db
    image: mongo:6.0
    # if arm64 architecture, use the following line instead
    # platform: linux/amd64
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      
      - TZ=${TZ}
    
    volumes: 
      - ${HOST_MONGODB}:${MONGODB}
      - ./users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro

    tmpfs:
      - /tmp
      
    restart: unless-stopped
      
  express:
    container_name: express
    image: jiminu/express_cat:0.8
    # if arm64 architecture, use the following line instead
    # platform: linux/amd64
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      
      - TZ=${TZ}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    expose:
      - ${NODE_PORT}

  backup:
    container_name: backup
    image: mongo:6
    depends_on:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - BACKUP_INTERVAL_SECONDS=${BACKUP_INTERVAL_SECONDS}
    volumes:
      - ${HOST_MONGODB_BACKUP}:/backups
    restart: unless-stopped
    command: >-
      sh -c '
        echo "[backup] starting backup loop with interval ${BACKUP_INTERVAL_SECONDS:-3600}s";
        while true; do 
          if mongosh --quiet \
            --host="$$MONGO_HOST" --port="$$MONGO_PORT" \
            -u "$$MONGO_INITDB_ROOT_USERNAME" -p "$$MONGO_INITDB_ROOT_PASSWORD" \
            --authenticationDatabase admin \
            --eval "db.adminCommand(\"ping\")" >/dev/null 2>&1; then
              ts=$$(date +%F-%H%M%S);
              outDir=/backups/dump-$$ts;
              echo "[backup] running mongodump to $$outDir";
              mongodump \
                --host="$$MONGO_HOST" --port="$$MONGO_PORT" \
                -u "$$MONGO_INITDB_ROOT_USERNAME" -p "$$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --out "$$outDir" && echo "[backup] success: $$outDir" || echo "[backup] mongodump failed";
          else
              echo "[backup] db not ready, will retry";
          fi;
          sleep $${BACKUP_INTERVAL_SECONDS:-3600};
        done'
